//
//  OpCodePrototypes.swift
//  Disassembler
//
//  Created by Jacques Légaré on 2020-03-13.
//  Copyright © 2020 Jacques Legare. All rights reserved.
//

import Foundation

enum ArgumentType {
    case address
    case relative
    case value
    case none
}

typealias AddressingMode = ( size: UInt8, type: ArgumentType, template: String )

let addressingModes: [ String: AddressingMode ] = [ "absolute" :    ( size: 3, type: .address,  template: "%@" ),
                                                    "absoluteX" :   ( size: 3, type: .address,  template: "%@,X" ),
                                                    "absoluteY" :   ( size: 3, type: .address,  template: "%@,Y" ),
                                                    "accumulator" : ( size: 1, type: .none,     template: "" ),
                                                    "immediate" :   ( size: 2, type: .value,    template: "#$%02x" ),
                                                    "implied" :     ( size: 1, type: .none,     template: "" ),
                                                    "indirect" :    ( size: 3, type: .address,  template: "(%@)" ),
                                                    "indirectX" :   ( size: 2, type: .address,  template: "(%@,X)" ),
                                                    "indirectY" :   ( size: 2, type: .address,  template: "(%@),Y" ),
                                                    "relative" :    ( size: 3, type: .relative, template: "%@" ),
                                                    "zeroPage" :    ( size: 2, type: .address,  template: "%@" ),
                                                    "zeroPageX" :   ( size: 2, type: .address,  template: "%@" ),
                                                    "zeroPageY" :   ( size: 2, type: .address,  template: "%@" ), ]

typealias OpCodePrototype = ( name: String, mode: AddressingMode )

let opCodesPrototypes: [ UInt8 : OpCodePrototype ] = [ 0x00 : ( name: "BRK", mode: addressingModes["implied"]! ),
                                                       0x01 : ( name: "ORA", mode: addressingModes["indirectX"]! ),
                                                       0x05 : ( name: "ORA", mode: addressingModes["zeroPage"]! ),
                                                       0x06 : ( name: "ASL", mode: addressingModes["zeroPage"]! ),
                                                       0x08 : ( name: "PHP", mode: addressingModes["implied"]! ),
                                                       0x09 : ( name: "ORA", mode: addressingModes["immediate"]! ),
                                                       0x0a : ( name: "ASL", mode: addressingModes["accumulator"]! ),
                                                       0x0d : ( name: "ORA", mode: addressingModes["absolute"]! ),
                                                       0x0e : ( name: "ASL", mode: addressingModes["absolute"]! ),
                                                       0x10 : ( name: "BPL", mode: addressingModes["relative"]! ),
                                                       0x11 : ( name: "ORA", mode: addressingModes["indirectY"]! ),
                                                       0x15 : ( name: "ORA", mode: addressingModes["zeroPageX"]! ),
                                                       0x16 : ( name: "ASL", mode: addressingModes["zeroPageX"]! ),
                                                       0x18 : ( name: "CLC", mode: addressingModes["implied"]! ),
                                                       0x19 : ( name: "ORA", mode: addressingModes["absoluteY"]! ),
                                                       0x1d : ( name: "ORA", mode: addressingModes["absoluteX"]! ),
                                                       0x1e : ( name: "ASL", mode: addressingModes["absoluteX"]! ),
                                                       0x20 : ( name: "JSR", mode: addressingModes["absolute"]! ),
                                                       0x21 : ( name: "AND", mode: addressingModes["indirectX"]! ),
                                                       0x24 : ( name: "BIT", mode: addressingModes["zeroPage"]! ),
                                                       0x25 : ( name: "AND", mode: addressingModes["zeroPage"]! ),
                                                       0x26 : ( name: "ROL", mode: addressingModes["zeroPage"]! ),
                                                       0x28 : ( name: "PLP", mode: addressingModes["implied"]! ),
                                                       0x29 : ( name: "AND", mode: addressingModes["immediate"]! ),
                                                       0x2a : ( name: "ROL", mode: addressingModes["accumulator"]! ),
                                                       0x2c : ( name: "BIT", mode: addressingModes["absolute"]! ),
                                                       0x2d : ( name: "AND", mode: addressingModes["absolute"]! ),
                                                       0x2e : ( name: "ROL", mode: addressingModes["absolute"]! ),
                                                       0x30 : ( name: "BMI", mode: addressingModes["relative"]! ),
                                                       0x31 : ( name: "AND", mode: addressingModes["indirectY"]! ),
                                                       0x35 : ( name: "AND", mode: addressingModes["zeroPageX"]! ),
                                                       0x36 : ( name: "ROL", mode: addressingModes["zeroPageX"]! ),
                                                       0x38 : ( name: "SEC", mode: addressingModes["implied"]! ),
                                                       0x39 : ( name: "AND", mode: addressingModes["absoluteY"]! ),
                                                       0x3d : ( name: "AND", mode: addressingModes["absoluteX"]! ),
                                                       0x3e : ( name: "ROL", mode: addressingModes["absoluteX"]! ),
                                                       0x40 : ( name: "RTI", mode: addressingModes["implied"]! ),
                                                       0x41 : ( name: "EOR", mode: addressingModes["indirectX"]! ),
                                                       0x45 : ( name: "EOR", mode: addressingModes["zeroPage"]! ),
                                                       0x46 : ( name: "LSR", mode: addressingModes["zeroPage"]! ),
                                                       0x48 : ( name: "PHA", mode: addressingModes["implied"]! ),
                                                       0x49 : ( name: "EOR", mode: addressingModes["immediate"]! ),
                                                       0x4a : ( name: "LSR", mode: addressingModes["accumulator"]! ),
                                                       0x4c : ( name: "JMP", mode: addressingModes["absolute"]! ),
                                                       0x4d : ( name: "EOR", mode: addressingModes["absolute"]! ),
                                                       0x4e : ( name: "LSR", mode: addressingModes["absolute"]! ),
                                                       0x50 : ( name: "BVC", mode: addressingModes["relative"]! ),
                                                       0x51 : ( name: "EOR", mode: addressingModes["indirectY"]! ),
                                                       0x55 : ( name: "EOR", mode: addressingModes["zeroPageX"]! ),
                                                       0x56 : ( name: "LSR", mode: addressingModes["zeroPageX"]! ),
                                                       0x58 : ( name: "CLI", mode: addressingModes["implied"]! ),
                                                       0x59 : ( name: "EOR", mode: addressingModes["absoluteY"]! ),
                                                       0x5d : ( name: "EOR", mode: addressingModes["absoluteX"]! ),
                                                       0x5e : ( name: "LSR", mode: addressingModes["absoluteX"]! ),
                                                       0x60 : ( name: "RTS", mode: addressingModes["implied"]! ),
                                                       0x61 : ( name: "ADC", mode: addressingModes["indirectX"]! ),
                                                       0x65 : ( name: "ADC", mode: addressingModes["zeroPage"]! ),
                                                       0x66 : ( name: "ROR", mode: addressingModes["zeroPage"]! ),
                                                       0x68 : ( name: "PLA", mode: addressingModes["implied"]! ),
                                                       0x69 : ( name: "ADC", mode: addressingModes["immediate"]! ),
                                                       0x6a : ( name: "ROR", mode: addressingModes["accumulator"]! ),
                                                       0x6c : ( name: "JMP", mode: addressingModes["indirect"]! ),
                                                       0x6d : ( name: "ADC", mode: addressingModes["absolute"]! ),
                                                       0x6e : ( name: "ROR", mode: addressingModes["absolute"]! ),
                                                       0x70 : ( name: "BVS", mode: addressingModes["relative"]! ),
                                                       0x71 : ( name: "ADC", mode: addressingModes["indirectY"]! ),
                                                       0x75 : ( name: "ADC", mode: addressingModes["zeroPageX"]! ),
                                                       0x76 : ( name: "ROR", mode: addressingModes["zeroPageX"]! ),
                                                       0x78 : ( name: "SEI", mode: addressingModes["implied"]! ),
                                                       0x79 : ( name: "ADC", mode: addressingModes["absoluteY"]! ),
                                                       0x7d : ( name: "ADC", mode: addressingModes["absoluteX"]! ),
                                                       0x7e : ( name: "ROR", mode: addressingModes["absoluteX"]! ),
                                                       0x81 : ( name: "STA", mode: addressingModes["indirectX"]! ),
                                                       0x84 : ( name: "STY", mode: addressingModes["zeroPage"]! ),
                                                       0x85 : ( name: "STA", mode: addressingModes["zeroPage"]! ),
                                                       0x86 : ( name: "STX", mode: addressingModes["zeroPage"]! ),
                                                       0x88 : ( name: "DEY", mode: addressingModes["implied"]! ),
                                                       0x8a : ( name: "TXA", mode: addressingModes["implied"]! ),
                                                       0x8c : ( name: "STY", mode: addressingModes["absolute"]! ),
                                                       0x8d : ( name: "STA", mode: addressingModes["absolute"]! ),
                                                       0x8e : ( name: "STX", mode: addressingModes["absolute"]! ),
                                                       0x90 : ( name: "BCC", mode: addressingModes["relative"]! ),
                                                       0x91 : ( name: "STA", mode: addressingModes["indirectY"]! ),
                                                       0x94 : ( name: "STY", mode: addressingModes["zeroPageX"]! ),
                                                       0x95 : ( name: "STA", mode: addressingModes["zeroPageX"]! ),
                                                       0x96 : ( name: "STX", mode: addressingModes["zeroPageY"]! ),
                                                       0x98 : ( name: "TYA", mode: addressingModes["implied"]! ),
                                                       0x99 : ( name: "STA", mode: addressingModes["absoluteY"]! ),
                                                       0x9a : ( name: "TXS", mode: addressingModes["implied"]! ),
                                                       0x9d : ( name: "STA", mode: addressingModes["absoluteX"]! ),
                                                       0xa0 : ( name: "LDY", mode: addressingModes["immediate"]! ),
                                                       0xa1 : ( name: "LDA", mode: addressingModes["indirectX"]! ),
                                                       0xa2 : ( name: "LDX", mode: addressingModes["immediate"]! ),
                                                       0xa4 : ( name: "LDY", mode: addressingModes["zeroPage"]! ),
                                                       0xa5 : ( name: "LDA", mode: addressingModes["zeroPage"]! ),
                                                       0xa6 : ( name: "LDX", mode: addressingModes["zeroPage"]! ),
                                                       0xa8 : ( name: "TAY", mode: addressingModes["implied"]! ),
                                                       0xa9 : ( name: "LDA", mode: addressingModes["immediate"]! ),
                                                       0xaa : ( name: "TAX", mode: addressingModes["implied"]! ),
                                                       0xac : ( name: "LDY", mode: addressingModes["absolute"]! ),
                                                       0xad : ( name: "LDA", mode: addressingModes["absolute"]! ),
                                                       0xae : ( name: "LDX", mode: addressingModes["absolute"]! ),
                                                       0xb0 : ( name: "BCS", mode: addressingModes["relative"]! ),
                                                       0xb1 : ( name: "LDA", mode: addressingModes["indirectY"]! ),
                                                       0xb4 : ( name: "LDY", mode: addressingModes["zeroPageX"]! ),
                                                       0xb5 : ( name: "LDA", mode: addressingModes["zeroPageX"]! ),
                                                       0xb6 : ( name: "LDX", mode: addressingModes["zeroPageY"]! ),
                                                       0xb8 : ( name: "CLV", mode: addressingModes["implied"]! ),
                                                       0xb9 : ( name: "LDA", mode: addressingModes["absoluteY"]! ),
                                                       0xba : ( name: "TSX", mode: addressingModes["implied"]! ),
                                                       0xbc : ( name: "LDY", mode: addressingModes["absoluteX"]! ),
                                                       0xbd : ( name: "LDA", mode: addressingModes["absoluteX"]! ),
                                                       0xbe : ( name: "LDX", mode: addressingModes["absoluteY"]! ),
                                                       0xc0 : ( name: "CPY", mode: addressingModes["immediate"]! ),
                                                       0xc1 : ( name: "CMP", mode: addressingModes["indirectX"]! ),
                                                       0xc4 : ( name: "CPY", mode: addressingModes["zeroPage"]! ),
                                                       0xc5 : ( name: "CMP", mode: addressingModes["zeroPage"]! ),
                                                       0xc6 : ( name: "DEC", mode: addressingModes["zeroPage"]! ),
                                                       0xc8 : ( name: "INY", mode: addressingModes["implied"]! ),
                                                       0xc9 : ( name: "CMP", mode: addressingModes["immediate"]! ),
                                                       0xca : ( name: "DEX", mode: addressingModes["implied"]! ),
                                                       0xcc : ( name: "CPY", mode: addressingModes["absolute"]! ),
                                                       0xcd : ( name: "CMP", mode: addressingModes["absolute"]! ),
                                                       0xce : ( name: "DEC", mode: addressingModes["absolute"]! ),
                                                       0xd0 : ( name: "BNE", mode: addressingModes["relative"]! ),
                                                       0xd1 : ( name: "CMP", mode: addressingModes["indirectY"]! ),
                                                       0xd5 : ( name: "CMP", mode: addressingModes["zeroPageX"]! ),
                                                       0xd6 : ( name: "DEC", mode: addressingModes["zeroPageX"]! ),
                                                       0xd8 : ( name: "CLD", mode: addressingModes["implied"]! ),
                                                       0xd9 : ( name: "CMP", mode: addressingModes["absoluteY"]! ),
                                                       0xdd : ( name: "CMP", mode: addressingModes["absoluteX"]! ),
                                                       0xde : ( name: "DEC", mode: addressingModes["absoluteX"]! ),
                                                       0xe0 : ( name: "CPX", mode: addressingModes["immediate"]! ),
                                                       0xe1 : ( name: "SBC", mode: addressingModes["indirectX"]! ),
                                                       0xe4 : ( name: "CPX", mode: addressingModes["zeroPage"]! ),
                                                       0xe5 : ( name: "SBC", mode: addressingModes["zeroPage"]! ),
                                                       0xe6 : ( name: "INC", mode: addressingModes["zeroPage"]! ),
                                                       0xe8 : ( name: "INX", mode: addressingModes["implied"]! ),
                                                       0xe9 : ( name: "SBC", mode: addressingModes["immediate"]! ),
                                                       0xea : ( name: "NOP", mode: addressingModes["implied"]! ),
                                                       0xec : ( name: "CPX", mode: addressingModes["absolute"]! ),
                                                       0xed : ( name: "SBC", mode: addressingModes["absolute"]! ),
                                                       0xee : ( name: "INC", mode: addressingModes["absolute"]! ),
                                                       0xf0 : ( name: "BEQ", mode: addressingModes["relative"]! ),
                                                       0xf1 : ( name: "SBC", mode: addressingModes["indirectY"]! ),
                                                       0xf5 : ( name: "SBC", mode: addressingModes["zeroPageX"]! ),
                                                       0xf6 : ( name: "INC", mode: addressingModes["zeroPageX"]! ),
                                                       0xf8 : ( name: "SED", mode: addressingModes["implied"]! ),
                                                       0xf9 : ( name: "SBC", mode: addressingModes["absoluteY"]! ),
                                                       0xfd : ( name: "SBC", mode: addressingModes["absoluteX"]! ),
                                                       0xfe : ( name: "INC", mode: addressingModes["absoluteX"]! ), ]

enum OpCode {
    case opCode(id: UInt8, name: String, mode: AddressingMode, arguments: [UInt8])
    case none(value: [UInt8])
}
